import { buildDomain, Entry } from "./build";

const PRODUCT: Entry[] = [
  ["How do you prioritise features on a roadmap?", "Product judgement.", "Tie to strategy and measurable goals | Frameworks: RICE (reach, impact, confidence, effort), impact versus effort, MoSCoW, Kano | Use data and user research, not opinions alone | Communicate trade-offs and what is deliberately not being done | Revisit regularly", "prioritization roadmap rice product"],
  ["Tell me about a product you love and how you would improve it.", "Product sense.", "Identify the target user and their core job to be done | Point out a real pain point with evidence | Propose one focused improvement rather than many | Define success metrics and risks | Consider trade-offs and how you would validate", "product-sense improvement metrics"],
  ["How do you define and track success for a new feature?", "Metrics thinking.", "Pick a primary success metric tied to the goal (adoption, activation, retention) | Add guardrail metrics for harm | Set a target and baseline | Instrument events before launch | Plan an experiment or staged rollout", "metrics kpi north-star experimentation"],
  ["How do you handle stakeholders who disagree on scope?", "Influence.", "Align on the goal and success criteria first | Use data and customer evidence | Make trade-offs visible (scope, time, quality) | Document decisions and rationale | Escalate only with clear options", "stakeholders scope communication negotiation"],
  ["Walk me through how you would launch a product.", "Execution.", "Discovery and problem validation | Define the MVP and success metrics | Beta or pilot with feedback | Go-to-market: positioning, channels, pricing, enablement | Launch monitoring and a rollback plan | Post-launch iteration", "launch go-to-market mvp execution"],
  ["How do you conduct user research and turn it into decisions?", "Discovery.", "Mix qualitative (interviews, usability tests) and quantitative (analytics, surveys) methods | Ask about past behaviour, not hypotheticals | Synthesise into themes and opportunities | Validate with prototypes | Avoid leading questions", "user-research discovery ux product"],
  ["A key metric dropped 10 percent. What do you do?", "Product analytics and execution.", "Confirm the data is correct and the drop is real | Segment by platform, geography, cohort and funnel step | Check recent releases, incidents and external factors | Form and test hypotheses | Decide on mitigation and communicate", "metrics debugging analytics product"],
  ["How do you write a good product requirements document or user story?", "Communication.", "State the problem, users and goals before the solution | User stories: As a user I want X so that Y, with acceptance criteria | Define scope and out-of-scope, success metrics and dependencies | Keep it concise and review with engineering and design", "prd user-stories requirements product"],
  ["MVP: what is it and how do you decide what goes in it?", "Product strategy.", "Minimum Viable Product tests the core value hypothesis with the least effort | Include only what is needed to learn | Define the riskiest assumptions and how the MVP tests them | It should still deliver real value, not just be a broken product", "mvp strategy lean product"],
  ["How do you work with engineers and designers?", "Collaboration.", "Involve them early in problem definition | Share context and customer evidence, not just specs | Respect estimates and technical constraints | Make trade-offs jointly | Keep regular feedback loops", "collaboration engineering design product"],
  ["How would you estimate the market size for a new product?", "Estimation.", "Top-down: total market narrowed by segments | Bottom-up: number of customers times price times frequency | State assumptions clearly and sanity-check with another method | Report TAM, SAM and SOM", "market-sizing estimation strategy product"],
  ["How do you decide when to kill a feature or product?", "Product judgement.", "Review usage, cost of maintenance, strategic fit and opportunity cost | Set clear criteria upfront | Communicate to affected users with alternatives and a timeline | Learn from the outcome", "sunset decision product strategy"],
];

const MARKETING: Entry[] = [
  ["How would you build a marketing plan for a new product?", "Marketing strategy.", "Define target audience and positioning | Set goals and budget | Choose channels (SEO, paid, email, social, partnerships) | Map the funnel (awareness, consideration, conversion, retention) | Define metrics and iterate on data", "marketing strategy funnel positioning"],
  ["Tell me about a time you closed a difficult deal or convinced a sceptical customer.", "Persuasion.", "Understand the objection and the buyer's real need | Tailor value to their goals with evidence | Build trust through consistency and honesty | Handle negotiation with options | Quantify the result", "sales persuasion negotiation customer"],
  ["How do you measure the ROI of a marketing campaign?", "Marketing analytics.", "ROI = (return minus cost) divided by cost | Track CAC, conversion rate, LTV and payback period | Attribution models (first touch, last touch, multi-touch) and their limits | Use a control or holdout to measure incrementality", "roi metrics campaign cac ltv"],
  ["What is the sales funnel and how do you improve conversion?", "Sales process.", "Stages: lead, qualified, opportunity, proposal, closed | Measure conversion between stages and find the biggest drop | Improve qualification, follow-up speed, messaging and objection handling | Use CRM data for coaching", "sales funnel conversion crm"],
  ["How do SEO and content marketing work together?", "Digital marketing.", "SEO improves organic visibility through technical health, relevant content and authority (links) | Content targets user intent and keywords | Measure rankings, organic traffic and conversions | Results compound over time but are slow", "seo content marketing digital"],
  ["What are CAC and LTV and why does their ratio matter?", "Unit economics.", "CAC is customer acquisition cost: total sales and marketing spend divided by new customers | LTV is the expected revenue or profit from a customer over their lifetime | LTV to CAC ratio around 3 or higher is a common healthy benchmark | Payback period matters for cash flow", "cac ltv unit-economics marketing"],
  ["How do you handle rejection and difficult prospects in sales?", "Resilience.", "Treat rejection as information; ask for feedback | Stay professional and keep the relationship | Adjust approach based on patterns | Maintain activity volume and follow-up discipline | Set realistic, process-based goals", "sales resilience rejection communication"],
  ["How would you segment customers and position a product?", "Marketing fundamentals.", "Segment by demographics, behaviour, needs or value | Choose target segments with attractive size and fit | Craft positioning: for whom, what category, key benefit, differentiator | Test messaging with real customers", "segmentation positioning stp marketing"],
];

export const business = [
  ...buildDomain("product-management", "PM", "question", PRODUCT),
  ...buildDomain("marketing-sales", "MKT", "question", MARKETING),
];
