import { buildDomain, Entry } from "./build";

const DSA: Entry[] = [
  ["What is Big-O notation and why does it matter?", "Algorithm analysis fundamentals.", "Describes how runtime or memory grows with input size n, ignoring constants and lower-order terms | Common classes in increasing order: O(1), O(log n), O(n), O(n log n), O(n^2), O(2^n), O(n!) | Usually describes worst-case upper bound; also mention average and amortised cases | Use it to compare approaches and predict scalability, e.g. choosing a hash map (O(1) average lookup) over a list scan (O(n))", "algorithms complexity big-o analysis"],
  ["Explain the difference between an array and a linked list.", "Core data structure trade-offs.", "Array: contiguous memory, O(1) index access, O(n) insert/delete in the middle, cache friendly | Singly linked list: nodes with pointers, O(1) insert/delete at a known node or head, O(n) access/search, extra memory per pointer | Dynamic arrays double capacity so append is amortised O(1) | Choose by access pattern", "array linked-list data-structures"],
  ["What is the difference between a stack and a queue?", "Basic abstract data types.", "Stack is LIFO: push and pop at one end | Queue is FIFO: enqueue at the back, dequeue at the front | Stack uses: function call stack, undo, DFS, expression parsing | Queue uses: BFS, scheduling, buffering | Both can be implemented with arrays or linked lists, operations O(1)", "stack queue data-structures lifo fifo"],
  ["How does a hash table work and how are collisions handled?", "Hashing fundamentals.", "A hash function maps a key to a bucket index | Average O(1) insert, lookup and delete; worst case O(n) with many collisions | Collision handling: separate chaining (linked list or tree per bucket) and open addressing (linear/quadratic probing, double hashing) | Load factor triggers resizing and rehashing | Keys must be hashable and consistent with equality", "hash-table hashmap collisions data-structures"],
  ["Explain binary search trees and why balancing matters.", "Tree data structures.", "BST property: left subtree keys smaller, right subtree keys larger | Average O(log n) search/insert/delete, but a sorted insertion order degrades an unbalanced BST to O(n) | Self-balancing trees such as AVL and red-black keep height O(log n) | In-order traversal of a BST yields sorted order", "bst tree balanced avl red-black data-structures"],
  ["Compare quicksort and merge sort.", "Sorting algorithm trade-offs.", "Quicksort: average O(n log n), worst case O(n^2) with bad pivots, in-place O(log n) stack space, not stable, usually fastest in practice | Merge sort: always O(n log n), stable, needs O(n) extra space, good for linked lists and external sorting | Mention pivot selection (random or median-of-three) | Comparison sorts cannot beat O(n log n) in the worst case", "sorting quicksort mergesort algorithms complexity"],
  ["Explain binary search and its requirements.", "Search algorithms.", "Requires a sorted (or monotonic) search space | Compare with the middle element and discard half each step | O(log n) time, O(1) space iteratively | Watch for off-by-one errors and integer overflow when computing mid | Can be applied to answers (binary search on the answer) not just arrays", "binary-search algorithms searching"],
  ["What is recursion and when would you avoid it?", "Recursion fundamentals.", "A function calling itself with a base case and a smaller subproblem | Each call uses stack space, so deep recursion risks stack overflow | Convert to iteration or use tail recursion where supported | Naive recursion can repeat work (e.g. Fibonacci is exponential) which memoisation fixes | Good for trees, divide-and-conquer, backtracking", "recursion algorithms stack"],
  ["What is dynamic programming? Explain memoisation versus tabulation.", "Optimisation technique.", "Applies to problems with overlapping subproblems and optimal substructure | Memoisation: top-down recursion with a cache | Tabulation: bottom-up filling a table iteratively | Turns exponential solutions into polynomial ones | Classic examples: Fibonacci, knapsack, longest common subsequence, coin change", "dynamic-programming memoization algorithms"],
  ["Compare DFS and BFS.", "Graph traversal.", "BFS uses a queue, explores level by level, finds shortest path in unweighted graphs | DFS uses a stack or recursion, goes deep first, uses less memory on wide graphs | Both O(V + E) with adjacency lists | DFS suits cycle detection, topological sort, connected components | BFS suits shortest path and level-order traversal", "bfs dfs graphs traversal algorithms"],
  ["How does Dijkstra's algorithm work?", "Shortest paths.", "Finds shortest paths from a source in graphs with non-negative edge weights | Greedy: repeatedly pick the unvisited node with the smallest distance using a priority queue (min-heap) | Relax outgoing edges | O((V + E) log V) with a binary heap | Fails with negative edges; use Bellman-Ford instead", "dijkstra shortest-path graphs greedy"],
  ["What is a heap and where is it used?", "Priority queue implementation.", "A complete binary tree satisfying the heap property (min-heap: parent <= children) | Stored efficiently in an array | Insert and extract-min are O(log n), peek is O(1), build-heap is O(n) | Used for priority queues, heap sort, top-k problems, Dijkstra, scheduling", "heap priority-queue data-structures"],
  ["How do you detect a cycle in a linked list?", "Classic linked list problem.", "Floyd's tortoise and hare: slow pointer moves one step, fast moves two; if they meet there is a cycle | O(n) time and O(1) space | Alternative: hash set of visited nodes uses O(n) space | To find the cycle start, reset one pointer to the head and move both one step at a time", "linked-list cycle two-pointers algorithms"],
  ["How would you solve the two-sum problem efficiently?", "Hash-based lookup.", "Brute force nested loops is O(n^2) | Use a hash map from value to index: for each element check whether target minus element is already in the map | O(n) time, O(n) space | If the array is sorted, two pointers give O(n) time with O(1) space | Discuss duplicates and returning indices versus values", "two-sum hashmap arrays algorithms"],
  ["How do you reverse a linked list?", "Pointer manipulation.", "Iterative: keep prev, curr, next; point curr.next to prev and advance | O(n) time, O(1) space | Recursive version uses O(n) call stack | Handle empty and single-node lists", "linked-list reverse pointers algorithms"],
  ["What is the sliding window technique?", "Array and string optimisation.", "Maintain a window over a contiguous range and update it incrementally | Reduces O(n*k) recomputation to O(n) | Fixed-size windows (max sum of k elements) and variable-size windows (longest substring without repeating characters) | Often combined with a hash map or counters", "sliding-window arrays strings algorithms"],
  ["What is a trie and when would you use it?", "Prefix tree.", "Tree where each node represents a character and paths represent prefixes | Insert and search take O(L) for a word of length L | Great for autocomplete, prefix search and spell checking | Uses more memory than a hash set | Compressed variants (radix tree) reduce space", "trie prefix-tree strings data-structures autocomplete"],
  ["Check whether two strings are anagrams. How would you do it?", "String handling.", "Sort both strings and compare: O(n log n) | Count character frequencies with an array or hash map: O(n) time | Handle case, spaces and Unicode assumptions | Early exit if lengths differ", "anagram strings hashing algorithms"],
  ["What is the time complexity of common operations on arrays, hash maps and trees?", "Complexity recall.", "Array: access O(1), search O(n), insert/delete O(n) except at end | Hash map: average O(1) insert/lookup/delete, worst O(n) | Balanced BST: O(log n) for search/insert/delete | Heap: insert O(log n), find-min O(1) | Sorting: O(n log n)", "complexity data-structures cheat-sheet"],
  ["What is the difference between a greedy algorithm and dynamic programming?", "Algorithm paradigms.", "Greedy makes the locally optimal choice at each step and never reconsiders; only correct when the greedy-choice property holds (e.g. activity selection, Huffman coding) | DP considers subproblem combinations and guarantees optimality when optimal substructure holds | Counter-example: greedy fails for arbitrary coin change while DP works", "greedy dynamic-programming algorithms paradigms"],
];

const OS: Entry[] = [
  ["Explain the difference between a process and a thread.", "OS fundamentals.", "A process has its own address space, resources and PCB | Threads within a process share code, heap and open files but each has its own stack and registers | Thread context switches are cheaper than process switches | Shared memory needs synchronisation; a crashing thread can bring down the whole process | Processes give isolation, threads give lightweight concurrency", "operating-systems concurrency threads processes"],
  ["What is a deadlock and what are the conditions for it?", "Concurrency hazards.", "Deadlock: processes wait forever for resources held by each other | Four Coffman conditions must all hold: mutual exclusion, hold and wait, no preemption, circular wait | Prevention: break one condition, e.g. impose a global lock ordering to avoid circular wait | Also detection and recovery, and avoidance with the Banker's algorithm", "deadlock concurrency operating-systems locks"],
  ["What is the difference between a mutex and a semaphore?", "Synchronisation primitives.", "Mutex: mutual exclusion lock with ownership, only the thread that locked it should unlock it | Semaphore: counter allowing up to N concurrent holders (binary semaphore is like a mutex without ownership) | Semaphores can signal between threads | Misuse can cause deadlock or priority inversion", "mutex semaphore synchronization concurrency"],
  ["Explain virtual memory and paging.", "Memory management.", "Virtual memory gives each process its own large logical address space mapped to physical memory | Memory is divided into fixed-size pages and frames; the page table maps virtual to physical pages | A TLB caches translations | A page fault loads a page from disk when it is not in RAM | Enables isolation and running programs larger than RAM", "virtual-memory paging memory-management operating-systems"],
  ["What is a context switch and why is it costly?", "Scheduling overhead.", "Saving the state of the running process/thread (registers, program counter) and loading another's | Costs CPU time, and disrupts caches and the TLB | Too many switches reduce throughput | Thread switches within a process are cheaper than process switches", "context-switch scheduling operating-systems performance"],
  ["Describe common CPU scheduling algorithms.", "Scheduling.", "FCFS: simple but suffers the convoy effect | Shortest Job First: optimal average waiting time but needs burst prediction and can starve long jobs | Round Robin: time quantum gives fairness for interactive systems | Priority scheduling can starve low-priority jobs, fixed with aging | Real systems use multilevel feedback queues", "scheduling cpu round-robin operating-systems"],
  ["What is a race condition and how do you prevent it?", "Concurrency correctness.", "Outcome depends on the timing of interleaved operations on shared data | Example: two threads incrementing a counter without synchronisation | Prevent with locks/mutexes, atomic operations, immutability, or message passing | Keep critical sections small | Test with thread sanitizers", "race-condition concurrency synchronization threads"],
  ["What is the difference between user mode and kernel mode, and what is a system call?", "OS protection model.", "Kernel mode has full hardware access; user mode is restricted | Programs request services (file I/O, process creation) through system calls, which trap into the kernel | This protects the system from faulty or malicious programs | Mode switches have a cost", "kernel system-call user-mode operating-systems"],
  ["What is the difference between the stack and the heap?", "Memory layout.", "Stack: per-thread, stores function frames and local variables, automatically allocated and freed, fast, limited size | Heap: dynamically allocated memory managed manually or by a garbage collector, larger and slower, shared across threads | Stack overflow from deep recursion; heap issues include leaks and fragmentation", "stack heap memory operating-systems"],
  ["What is thrashing?", "Memory performance problem.", "System spends more time swapping pages in and out than executing | Occurs when the working sets of running processes exceed available RAM | Fixes: reduce multiprogramming degree, add RAM, use working-set or page-fault-frequency based allocation", "thrashing paging memory operating-systems"],
  ["What are the ways processes communicate (IPC)?", "Inter-process communication.", "Pipes and named pipes | Message queues | Shared memory (fastest, needs synchronisation) | Sockets (also across machines) | Signals for simple notifications", "ipc pipes shared-memory sockets operating-systems"],
  ["Explain the producer-consumer problem.", "Classic synchronisation problem.", "Producers add items to a bounded buffer and consumers remove them | Need mutual exclusion on the buffer plus signalling when the buffer is full or empty | Solved with two counting semaphores (empty, full) and a mutex, or condition variables/blocking queues | Avoids busy waiting and races", "producer-consumer semaphores concurrency synchronization"],
];

const NETWORKING: Entry[] = [
  ["What happens when you type a URL into the browser and press enter?", "Networking breadth end to end.", "Browser checks caches then resolves the domain through DNS | Opens a TCP connection (three-way handshake) and, for HTTPS, a TLS handshake | Sends an HTTP request; server processes it and returns a response | Browser parses HTML, fetches CSS/JS/images and renders the page | Mention CDN, load balancers and caching", "networking http dns browser fundamentals"],
  ["What is the difference between TCP and UDP?", "Transport layer.", "TCP: connection-oriented, reliable, ordered delivery, retransmission, flow and congestion control; used by HTTP, SSH, email | UDP: connectionless, no delivery guarantee, lower latency and overhead; used for DNS, streaming, gaming, VoIP | Choose based on reliability versus latency needs", "tcp udp transport networking"],
  ["Explain the TCP three-way handshake.", "Connection setup.", "SYN: client sends a synchronise request with an initial sequence number | SYN-ACK: server acknowledges and sends its own sequence number | ACK: client acknowledges, connection established | Connection teardown uses FIN/ACK exchanges | SYN floods exploit half-open connections", "tcp handshake networking"],
  ["What is the difference between HTTP and HTTPS?", "Secure web communication.", "HTTPS is HTTP over TLS, giving encryption, integrity and server authentication | The TLS handshake negotiates keys using certificates issued by trusted certificate authorities | Symmetric encryption is used for data after the handshake | Prevents eavesdropping and tampering, required for modern browsers features", "https tls http security networking"],
  ["Explain common HTTP methods and status codes.", "HTTP fundamentals.", "GET reads (safe, idempotent), POST creates, PUT replaces (idempotent), PATCH partially updates, DELETE removes (idempotent) | 2xx success (200 OK, 201 Created, 204 No Content), 3xx redirects (301, 302, 304), 4xx client errors (400, 401, 403, 404, 429), 5xx server errors (500, 502, 503) | 401 means unauthenticated, 403 means forbidden", "http rest methods status-codes networking"],
  ["How does DNS work?", "Name resolution.", "Translates domain names to IP addresses | Resolver checks its cache, then queries root servers, TLD servers and the authoritative name server | Records include A, AAAA, CNAME, MX, TXT | Results are cached according to TTL | DNS can be used for load distribution and failover", "dns networking resolution"],
  ["What is the difference between the OSI model and the TCP/IP model?", "Network layering.", "OSI has 7 layers: physical, data link, network, transport, session, presentation, application | TCP/IP has 4 layers: link, internet, transport, application | OSI is a conceptual reference; TCP/IP is what the internet uses | Examples: IP at network layer, TCP/UDP at transport, HTTP at application", "osi tcp-ip layers networking"],
  ["What is a load balancer and what algorithms does it use?", "Traffic distribution.", "Distributes requests across servers for scalability and availability | Layer 4 (transport) and Layer 7 (application) balancing | Algorithms: round robin, least connections, IP hash, weighted variants | Uses health checks to remove failed servers | Sticky sessions can be required for stateful apps", "load-balancer scalability networking availability"],
  ["What is CORS and why does it exist?", "Browser security policy.", "Browsers enforce the same-origin policy, blocking scripts from reading responses from other origins | CORS lets a server opt in with headers such as Access-Control-Allow-Origin | Non-simple requests trigger a preflight OPTIONS request | CORS is enforced by browsers, not servers; it does not replace authentication", "cors browser security http"],
  ["WebSockets versus HTTP polling: when would you use each?", "Real-time communication.", "HTTP polling repeatedly requests updates: simple but wasteful and higher latency | Long polling holds requests open | WebSocket gives a persistent full-duplex connection after an HTTP upgrade, low latency for chat, live dashboards, games | Server-Sent Events are simple one-way server push | WebSockets need scaling considerations such as sticky sessions or a pub/sub backend", "websocket polling realtime networking"],
  ["What is the difference between latency, bandwidth and throughput?", "Network performance vocabulary.", "Latency: time for a single packet or request to travel | Bandwidth: maximum data rate of a link | Throughput: actual achieved data rate | High bandwidth does not fix high latency | Reduce latency with CDNs, caching, fewer round trips, keep-alive and HTTP/2", "latency bandwidth throughput performance networking"],
];

const DATABASES: Entry[] = [
  ["What is the difference between SQL and NoSQL databases and how do you choose?", "Data-storage judgement.", "SQL: relational tables with a fixed schema, joins, strong ACID transactions, vertical scaling traditionally | NoSQL: document, key-value, column-family and graph stores with flexible schemas, built for horizontal scaling, often eventual consistency | Choose SQL for structured, relational data needing integrity; NoSQL for flexible schema, huge scale or specific access patterns | Many systems use both", "database sql nosql design"],
  ["Explain ACID properties in databases.", "Transaction guarantees.", "Atomicity: all operations of a transaction happen or none do | Consistency: transactions move the database between valid states respecting constraints | Isolation: concurrent transactions do not interfere | Durability: committed data survives crashes | Example: a bank transfer debiting and crediting accounts", "acid transactions database consistency"],
  ["What is database normalisation? Explain 1NF, 2NF and 3NF.", "Schema design.", "Organising data to reduce redundancy and anomalies | 1NF: atomic values, no repeating groups | 2NF: 1NF plus no partial dependency of non-key attributes on part of a composite key | 3NF: 2NF plus no transitive dependencies | Denormalisation is sometimes used deliberately for read performance", "normalization 1nf 2nf 3nf database design"],
  ["What is a database index and what are its trade-offs?", "Query performance.", "A data structure (commonly a B-tree) that speeds up lookups and range queries | Trade-off: faster reads but slower writes and extra storage | Composite index column order matters (leftmost prefix) | Use EXPLAIN to check usage | Avoid indexing low-selectivity columns or over-indexing", "index sql performance database b-tree"],
  ["Explain the different types of SQL joins.", "SQL fundamentals.", "INNER JOIN returns matching rows in both tables | LEFT JOIN returns all left rows plus matches, with NULLs for no match | RIGHT JOIN is the mirror | FULL OUTER JOIN returns all rows from both | CROSS JOIN gives the Cartesian product | Self-joins join a table with itself", "sql joins database queries"],
  ["What is the difference between a primary key, foreign key and unique key?", "Constraints.", "Primary key uniquely identifies a row, cannot be NULL, one per table | Foreign key references a primary key in another table to enforce referential integrity | Unique key enforces uniqueness but allows a NULL (in most databases) and a table can have several | Consider cascading deletes/updates", "primary-key foreign-key constraints database"],
  ["What are transaction isolation levels?", "Concurrency control.", "Read Uncommitted allows dirty reads | Read Committed prevents dirty reads | Repeatable Read prevents non-repeatable reads (phantoms may still occur depending on the DB) | Serializable prevents all anomalies with the highest cost | Higher isolation trades performance for correctness | Anomalies: dirty read, non-repeatable read, phantom read", "isolation transactions concurrency database"],
  ["Write a query to find the second-highest salary.", "SQL problem solving.", "Subquery: SELECT MAX(salary) FROM employees WHERE salary < (SELECT MAX(salary) FROM employees) | Or DENSE_RANK() over salary DESC and filter rank = 2 | Or ORDER BY salary DESC LIMIT 1 OFFSET 1 with DISTINCT | Discuss ties and NULL handling", "sql query window-functions subquery"],
  ["What is the difference between WHERE and HAVING, and GROUP BY?", "SQL aggregation.", "WHERE filters rows before grouping | GROUP BY groups rows for aggregates such as COUNT, SUM, AVG | HAVING filters groups after aggregation | Order of execution: FROM, WHERE, GROUP BY, HAVING, SELECT, ORDER BY", "sql group-by having aggregation"],
  ["What is the difference between DELETE, TRUNCATE and DROP?", "SQL commands.", "DELETE removes selected rows, can use WHERE, is logged row by row and can be rolled back | TRUNCATE removes all rows quickly, resets identity, typically minimal logging | DROP removes the table structure itself | DELETE and TRUNCATE keep the table definition", "sql delete truncate drop database"],
  ["What is the N+1 query problem and how do you fix it?", "ORM and query performance.", "Fetching a list with one query then issuing one query per item, causing N+1 queries | Fix with joins or eager loading, batching (IN queries) or data loaders | Detect with query logs and profiling", "n+1 orm performance database queries"],
  ["Explain database replication versus sharding.", "Scaling databases.", "Replication copies data to replicas for read scaling and availability (leader-follower, replication lag) | Sharding partitions data across nodes (by key or range) to scale writes and storage | Sharding adds complexity: cross-shard queries, rebalancing, hot shards | Choose shard keys carefully", "replication sharding scaling database"],
  ["What are window functions in SQL?", "Advanced SQL.", "Compute values across a set of rows related to the current row without collapsing them | Syntax uses OVER (PARTITION BY ... ORDER BY ...) | Examples: ROW_NUMBER, RANK, DENSE_RANK, LAG, LEAD, running totals with SUM OVER | Used for ranking, moving averages and comparisons with previous rows", "sql window-functions analytics"],
  ["Optimistic versus pessimistic locking?", "Concurrency control strategies.", "Pessimistic: lock rows up front (SELECT ... FOR UPDATE) to prevent conflicts, safe but reduces concurrency | Optimistic: no lock, check a version or timestamp at write time and retry on conflict, suits low-contention workloads | Choose based on contention level", "locking concurrency database optimistic pessimistic"],
  ["What are views and stored procedures?", "Database objects.", "View: a stored query presenting a virtual table, useful for abstraction and access control | Stored procedure: precompiled SQL logic on the server, can take parameters and reduce network round trips | Trade-offs: business logic in the database is harder to version and test", "views stored-procedures sql database"],
];

const OOP: Entry[] = [
  ["What are the four pillars of object-oriented programming?", "OOP fundamentals.", "Encapsulation: bundle data and methods, hide internal state behind an interface | Abstraction: expose essential behaviour, hide complexity | Inheritance: reuse and extend behaviour from a parent class | Polymorphism: the same interface with different implementations (overriding and overloading) | Give a code example for each", "oop encapsulation abstraction inheritance polymorphism"],
  ["What are the SOLID principles? Give an example of one.", "Design knowledge.", "Single Responsibility: a class should have one reason to change | Open/Closed: open for extension, closed for modification | Liskov Substitution: subtypes must be usable wherever the base type is expected | Interface Segregation: prefer small specific interfaces | Dependency Inversion: depend on abstractions, not concretions | Illustrate one with a real code example", "oop solid design-patterns"],
  ["Inheritance versus composition: which do you prefer and why?", "Design judgement.", "Inheritance models 'is-a' but creates tight coupling and fragile hierarchies | Composition models 'has-a', is more flexible and easier to test and change | Guideline: favour composition over inheritance | Inheritance is fine for genuine subtyping and shared behaviour", "oop composition inheritance design"],
  ["What is the difference between an abstract class and an interface?", "Language design.", "Interface defines a contract without state (in many languages, default methods aside) and a class can implement many | Abstract class can hold state and partial implementation, with single inheritance in most languages | Use interfaces for capabilities, abstract classes for shared base behaviour", "oop interface abstract-class design"],
  ["Explain polymorphism, overloading and overriding.", "OOP detail.", "Polymorphism lets code work with a base type while running derived behaviour | Overloading: same method name, different parameters, resolved at compile time | Overriding: subclass redefines a method, resolved at runtime via dynamic dispatch", "polymorphism overloading overriding oop"],
  ["Name common design patterns and when you would use them.", "Design patterns.", "Singleton: single instance (use sparingly, hidden global state) | Factory: create objects without specifying the concrete class | Observer: notify dependents when state changes (event systems) | Strategy: swap algorithms at runtime | Decorator: add behaviour dynamically | Adapter: convert an interface | Patterns are tools, not goals", "design-patterns singleton factory observer strategy"],
  ["What is dependency injection and why is it useful?", "Decoupling.", "Dependencies are supplied from outside instead of created inside a class | Improves testability (inject mocks) and reduces coupling | Forms: constructor, setter, or a DI container | Supports the Dependency Inversion Principle", "dependency-injection design testing oop"],
  ["What do DRY, KISS and YAGNI mean?", "Engineering principles.", "DRY: do not repeat knowledge or logic | KISS: keep solutions simple | YAGNI: do not build features until needed | Balance: over-applying DRY can create wrong abstractions", "dry kiss yagni principles clean-code"],
  ["What is immutability and why does it help?", "Programming style.", "Immutable objects cannot change after creation | Easier reasoning, thread safety with no synchronisation, safe sharing and caching | Costs: creating new objects for changes, mitigated by structural sharing | Widely used in functional programming and React state", "immutability concurrency functional design"],
  ["How do you handle errors and exceptions well?", "Robust code.", "Fail fast with clear messages | Catch exceptions only where you can handle them, do not swallow them silently | Use custom exception types and preserve the cause | Clean up resources with finally or using/with | Log with context and avoid exposing internals to users", "exceptions error-handling robustness clean-code"],
  ["What makes code clean and when do you refactor?", "Code quality.", "Meaningful names, small focused functions, low coupling, tests | Refactor when adding features, fixing bugs or spotting duplication, backed by tests | Keep behaviour unchanged while improving structure | Avoid big-bang rewrites", "clean-code refactoring quality maintainability"],
  ["Explain garbage collection and memory leaks in managed languages.", "Runtime memory.", "Garbage collector frees objects no longer reachable from roots | Approaches include reference counting and tracing (mark-and-sweep, generational) | Leaks still occur when references are unintentionally retained (caches, listeners, closures) | Profile heap snapshots to find them", "garbage-collection memory-leaks runtime performance"],
];

const ENGINEERING: Entry[] = [
  ["How do you approach debugging a production issue?", "Systematic problem solving.", "Assess impact and mitigate first (rollback, feature flag) | Reproduce and gather evidence: logs, metrics, traces, recent deploys | Form and test hypotheses, narrowing scope | Fix the root cause, add tests | Write a blameless post-mortem with follow-up actions", "debugging production troubleshooting incident"],
  ["How do you ensure the quality of the code you write?", "Engineering discipline.", "Testing pyramid: many unit tests, fewer integration tests, few end-to-end tests | Code reviews, linters and static analysis | CI running tests on every change | Meaningful coverage, not just a number | Examples from your own projects", "testing quality code-review ci"],
  ["Explain Git branching and how you handle merge conflicts.", "Tooling and teamwork.", "Short-lived feature branches merged via pull requests | Merge preserves history, rebase creates linear history (never rebase shared branches) | Conflicts arise when the same lines change; resolve by understanding both changes, then test | Keep commits small and messages clear | Pull or rebase frequently to reduce conflicts", "git version-control collaboration merge"],
  ["What makes a good code review?", "Collaboration.", "Review for correctness, readability, tests, security and design | Be specific, kind and explain reasoning | Keep pull requests small | Automate style checks so humans focus on logic | Authors respond openly to feedback", "code-review collaboration quality"],
  ["What is CI/CD?", "Delivery practice.", "Continuous Integration: merge often and automatically build and test | Continuous Delivery: every passing change is deployable | Continuous Deployment: passing changes deploy automatically | Benefits: faster feedback, smaller releases, lower risk | Tools such as GitHub Actions, Jenkins, GitLab CI", "ci cd pipeline automation devops"],
  ["Explain Agile and Scrum.", "Process knowledge.", "Agile values working software, collaboration and responding to change | Scrum: sprints of 1-4 weeks, roles (product owner, scrum master, developers), events (planning, daily stand-up, review, retrospective), artefacts (backlog, increment) | Kanban visualises flow and limits work in progress", "agile scrum kanban process"],
  ["What is technical debt and how do you manage it?", "Long-term thinking.", "Shortcuts that speed delivery now but increase future cost | Make it visible in the backlog with impact and cost | Pay it down incrementally alongside features | Prevent it with reviews, tests, and design discussion | Some debt is a conscious, tracked trade-off", "technical-debt maintainability planning"],
  ["What is test-driven development?", "Testing methodology.", "Red-green-refactor: write a failing test, make it pass with minimal code, then refactor | Drives simple, testable design | Provides a regression safety net | Not every situation suits strict TDD, e.g. exploratory UI work", "tdd testing methodology quality"],
  ["How do you estimate software tasks?", "Planning.", "Break work into small tasks | Use past velocity or reference stories, give ranges not single numbers | Include testing, review and unknowns | Communicate uncertainty and update estimates as you learn | Spikes reduce uncertainty", "estimation planning agile"],
  ["Unit, integration and end-to-end tests: what is the difference?", "Testing strategy.", "Unit tests check a small unit in isolation, fast and numerous | Integration tests check components working together, e.g. with a database | End-to-end tests exercise the whole system like a user, slow and brittle | Mocks and stubs isolate dependencies | Balance follows the testing pyramid", "testing unit integration e2e quality"],
  ["How do you profile and improve application performance?", "Performance engineering.", "Measure first with profilers, metrics and tracing; do not guess | Find the actual bottleneck (CPU, memory, I/O, database, network) | Fix the biggest one (algorithmic improvements, caching, batching, indexing) | Re-measure to confirm improvement | Avoid premature optimisation", "performance profiling optimization measurement"],
];

export const csFundamentals = [
  ...buildDomain("dsa", "DSA", "question", DSA),
  ...buildDomain("operating-systems", "OS", "question", OS),
  ...buildDomain("networking", "NET", "question", NETWORKING),
  ...buildDomain("databases", "DB", "question", DATABASES),
  ...buildDomain("oop-design", "OOP", "question", OOP),
  ...buildDomain("engineering-practices", "ENG", "question", ENGINEERING),
];
