import { buildDomain, Entry } from "./build";

const SYSTEM_DESIGN: Entry[] = [
  ["Design a URL shortener.", "Classic system design.", "Clarify requirements: create short links, redirect, expiry, analytics, scale (reads far exceed writes) | Generate unique short codes: base62 encoding of a counter or ID, or random codes with collision checks | Store mapping in a key-value or SQL store with an index on the code | Use 301 (permanent) versus 302 (temporary, allows analytics) redirects deliberately | Cache hot links (Redis) and use a CDN | Discuss sharding and rate limiting", "system-design scalability url-shortener"],
  ["How would you design a chat application?", "Real-time system design.", "Persistent connections via WebSockets | Message service, persistence and delivery status (sent, delivered, read) | Fan-out for group chats | Presence and typing indicators | Store messages in a scalable store partitioned by conversation | Use a pub/sub layer to route messages across servers | Handle offline delivery with push notifications and ordering with sequence numbers", "system-design realtime websockets messaging"],
  ["How do you scale a system from 1,000 to 1,000,000 users?", "Scaling approach.", "Measure and find the bottleneck first | Stateless app servers behind a load balancer | Caching and CDN | Database read replicas, then sharding | Asynchronous processing with queues | Monitoring and autoscaling | Avoid premature complexity", "scalability load-balancing sharding caching"],
  ["Explain the CAP theorem.", "Distributed systems theory.", "In the presence of a network partition a distributed store must choose between consistency and availability | Partition tolerance is required in practice | CP systems refuse or delay requests to stay consistent (e.g. many consensus-based stores) | AP systems stay available with eventual consistency (e.g. Dynamo-style stores) | PACELC extends this with the latency versus consistency trade-off when there is no partition", "distributed-systems cap consistency"],
  ["Design a rate limiter.", "Algorithmic system design.", "Algorithms: token bucket (allows bursts), leaky bucket, fixed window (boundary burst issue), sliding window log/counter | Store counters in Redis with atomic operations or Lua scripts for a distributed limiter | Key by user, IP or API key | Return 429 with Retry-After | Decide fail-open versus fail-closed when the limiter store is down", "rate-limiter redis algorithms"],
  ["How would you design a notification system?", "Asynchronous design.", "API accepts events and enqueues them | Workers per channel (email, SMS, push) | Retries with exponential backoff and dead-letter queues | Deduplication and idempotency keys | User preferences and quiet hours | Rate limiting per user and provider | Templates and delivery tracking", "notifications queue design async"],
  ["Design a news feed.", "Fan-out design.", "Fan-out on write (precompute feeds when a post is created) gives fast reads but is expensive for users with many followers | Fan-out on read computes at request time, cheaper writes but slower reads | Hybrid: push for normal users, pull for celebrities | Cache timelines in Redis | Ranking, pagination with cursors", "system-design feed fan-out social"],
  ["Explain LRU cache and how to implement it.", "Caching data structure.", "Evicts the least recently used item when full | Implement with a hash map plus a doubly linked list for O(1) get and put | Move an item to the front on access, evict from the tail | Alternatives: LFU, FIFO | Thread-safety needs locking", "lru cache data-structures design"],
  ["What is consistent hashing and why is it used?", "Distributed data placement.", "Maps both keys and nodes onto a hash ring; a key belongs to the next node clockwise | Adding or removing a node only remaps a small fraction of keys, unlike modulo hashing | Virtual nodes balance load | Used in distributed caches and databases", "consistent-hashing distributed-systems sharding"],
  ["What load balancing strategies exist?", "Traffic distribution.", "Round robin, least connections, weighted, IP hash for stickiness | Layer 4 versus Layer 7 balancing | Health checks and failover | Global load balancing with DNS or anycast | Avoid the load balancer itself being a single point of failure", "load-balancing scalability availability"],
  ["What does a CDN do and when do you use it?", "Content delivery.", "Caches static content at edge locations near users, reducing latency and origin load | Works with cache headers (Cache-Control, ETag) and invalidation/purge | Also helps with DDoS mitigation and TLS termination | Useful for images, scripts, video and cacheable API responses", "cdn caching performance latency"],
  ["How does database sharding work and what are its challenges?", "Data partitioning.", "Split data across nodes by a shard key (hash or range) | Improves write and storage scalability | Challenges: hot shards, cross-shard joins and transactions, rebalancing, choosing a shard key that distributes evenly | Consider replication and read replicas first", "sharding partitioning database scalability"],
  ["Message queue versus publish/subscribe?", "Messaging patterns.", "Queue: each message is consumed by one consumer (work distribution) | Pub/sub: each subscriber gets a copy (event broadcasting) | Kafka combines both with consumer groups and an append-only replayable log | Consider ordering, delivery guarantees (at-most-once, at-least-once, exactly-once) and backpressure", "messaging queue pubsub kafka distributed"],
  ["What is eventual consistency and where is it acceptable?", "Consistency models.", "Replicas converge to the same value if no new updates occur, but reads may temporarily be stale | Acceptable for feeds, likes, counters, DNS | Not acceptable for account balances or inventory without extra care | Techniques: read-your-writes, quorum reads and writes, conflict resolution (last-write-wins, CRDTs)", "eventual-consistency distributed-systems consistency"],
  ["Design a file storage service like Dropbox.", "Storage system design.", "Chunk files, store chunks in object storage, and keep metadata in a database | Deduplicate chunks with hashes | Sync clients detect changes and upload only changed chunks | Versioning and sharing permissions | Notifications for sync via long polling or WebSockets | Replication for durability", "system-design storage file-sync"],
  ["Design search autocomplete.", "Low-latency design.", "Use a trie or prefix index with top-k suggestions cached per prefix | Rank by frequency and recency from aggregated query logs, updated offline | Serve from memory or Redis with a CDN or edge cache | Debounce on the client | Handle typos and personalisation separately", "system-design autocomplete trie search"],
  ["Design a parking lot (low-level design).", "Object-oriented design.", "Clarify requirements: vehicle types, spot sizes, floors, pricing | Classes such as ParkingLot, Level, Spot, Vehicle, Ticket, PaymentStrategy | Use enums and polymorphism (Vehicle subclasses) and the Strategy pattern for pricing | Handle concurrency for spot allocation | Discuss extensibility", "low-level-design oop design parking-lot"],
];

const DEVOPS: Entry[] = [
  ["Explain what a CI/CD pipeline is and how you would set one up.", "Delivery automation.", "Stages: build, lint, unit tests, integration tests, package artifact, deploy to staging, then production | Triggered on pull requests and merges | Fail fast and cache dependencies | Deployment strategies with rollback | Tools: GitHub Actions, GitLab CI, Jenkins", "ci cd pipeline automation github-actions"],
  ["What is the difference between a container and a virtual machine?", "Infrastructure basics.", "VMs virtualise hardware and run a full guest OS on a hypervisor, heavier and more isolated | Containers share the host kernel and isolate processes using namespaces and cgroups, lightweight and fast to start | Docker images are layered and immutable | Containers give less isolation than VMs", "docker containers virtualization"],
  ["How does Kubernetes manage application availability?", "Orchestration.", "Pods are the smallest unit; Deployments manage ReplicaSets and rolling updates | Self-healing restarts failed containers and reschedules pods | Liveness and readiness probes | Services provide stable networking and load balancing | Horizontal Pod Autoscaler scales on metrics | ConfigMaps and Secrets manage configuration", "kubernetes orchestration availability scaling"],
  ["How do you monitor a production system?", "Observability.", "Three pillars: metrics, logs and traces | Define SLIs and SLOs and alert on user-impacting symptoms | Golden signals: latency, traffic, errors, saturation | Dashboards and on-call runbooks | Avoid alert fatigue", "monitoring observability logging alerting sre"],
  ["What is infrastructure as code and why use it?", "Automation mindset.", "Define infrastructure in versioned code (Terraform, CloudFormation, Pulumi) | Benefits: reproducibility, review through pull requests, drift detection, faster recovery | Declarative approach describes desired state | Keep state secure and remote", "iac terraform automation cloud"],
  ["How would you secure a cloud deployment?", "Cloud security.", "Least-privilege IAM and no long-lived root credentials | Secrets in a secret manager | Network segmentation with private subnets and security groups | Encryption at rest and in transit | Patching, logging and audit trails | Enable multi-factor authentication", "security cloud iam aws encryption"],
  ["What are good practices for writing Dockerfiles?", "Container craft.", "Use small, specific base images and multi-stage builds | Order layers to maximise cache use (install dependencies before copying source) | Run as a non-root user | Pin versions and use .dockerignore | Do not bake secrets into images", "docker dockerfile containers best-practices"],
  ["Blue-green versus canary deployments?", "Release strategies.", "Blue-green: two identical environments, switch traffic at once, instant rollback, double the infrastructure | Canary: route a small percentage of traffic to the new version, monitor, then increase | Rolling: replace instances gradually | Feature flags decouple deployment from release", "deployment blue-green canary release devops"],
  ["What are SLIs, SLOs and SLAs?", "Reliability vocabulary.", "SLI: a measured indicator such as request latency or availability | SLO: the internal target for an SLI, e.g. 99.9 percent availability | SLA: a contractual promise with consequences | Error budget is 100 percent minus the SLO and guides release pace", "sre slo sla reliability"],
  ["How do you handle an incident and run a post-mortem?", "Operational maturity.", "Detect, triage and mitigate first (rollback, failover) before root-causing | Communicate status clearly | Post-mortem is blameless, with a timeline, root cause, impact and action items with owners | Track follow-ups to completion", "incident post-mortem sre operations"],
  ["What is auto-scaling and how does it work?", "Elasticity.", "Automatically adds or removes instances based on metrics like CPU, request rate or queue length | Needs stateless instances and quick startup | Set minimum, maximum and cooldown to avoid flapping | Combine reactive and scheduled scaling", "autoscaling cloud scalability elasticity"],
  ["Serverless: what are the benefits and trade-offs?", "Cloud architecture.", "Pay per invocation, no server management, automatic scaling | Trade-offs: cold starts, execution time limits, vendor lock-in, harder local testing and debugging | Good for event-driven and spiky workloads | Watch cost at sustained high volume", "serverless lambda cloud architecture"],
  ["Object, block and file storage: what is the difference?", "Cloud storage.", "Object storage (S3): flat namespace, highly durable and scalable, accessed by HTTP, ideal for media and backups | Block storage (EBS): raw volumes attached to a server, low latency, for databases and OS disks | File storage (EFS/NFS): shared hierarchical file system", "s3 storage cloud aws"],
  ["What is a VPC and how do subnets and security groups work?", "Cloud networking.", "A Virtual Private Cloud is an isolated virtual network | Public subnets have a route to an internet gateway, private subnets do not and use a NAT gateway for outbound access | Security groups are stateful instance-level firewalls; network ACLs are stateless subnet-level | Place databases in private subnets", "vpc networking cloud security aws"],
  ["Logs, metrics and traces: how do they differ?", "Observability.", "Logs are discrete event records for detail | Metrics are numeric time series for trends and alerting | Traces follow a request across services to find latency bottlenecks | Use correlation ids to link them | Structured logging aids searching", "observability logging metrics tracing"],
  ["What is GitOps?", "Deployment model.", "Git is the single source of truth for declarative infrastructure and application state | A controller (Argo CD, Flux) reconciles the cluster to match Git | Provides audit history, easy rollback via revert, and review workflow", "gitops kubernetes deployment devops"],
  ["Which Linux commands do you use to diagnose a slow or failing server?", "Practical operations.", "top or htop for CPU and memory, free -m, df -h and du for disk | iostat/vmstat for I/O | netstat or ss for connections, curl and ping for reachability | journalctl and tail -f for logs | lsof for open files and ports", "linux troubleshooting commands operations"],
];

export const systemsCloud = [
  ...buildDomain("system-design", "SD", "question", SYSTEM_DESIGN),
  ...buildDomain("devops-cloud", "DEV", "question", DEVOPS),
];
